"""add crowd status

Revision ID: 0768645bdd7c
Revises: 45e1318a2f77
Create Date: 2026-06-28 11:08:21.315930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0768645bdd7c'
down_revision: Union[str, Sequence[str], None] = '45e1318a2f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crowd_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_data_id', sa.Integer(), nullable=False),
    sa.Column('crowd_score', sa.Float(), nullable=False),
    sa.Column('crowd_label', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sensor_data_id'], ['sensor_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_status_id'), 'crowd_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crowd_status_id'), table_name='crowd_status')
    op.drop_table('crowd_status')
    # ### end Alembic commands ###
