"""add created_at and updated_at

Revision ID: 3bec5bba2cb7
Revises: a9dbdd6eae9b
Create Date: 2026-06-29 04:34:21.670847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bec5bba2cb7'
down_revision: Union[str, Sequence[str], None] = 'a9dbdd6eae9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('devices', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('queue_status', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue_status', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('devices', 'updated_at')
    op.drop_column('devices', 'created_at')
    # ### end Alembic commands ###
