"""change crowd to queue

Revision ID: a9dbdd6eae9b
Revises: 0768645bdd7c
Create Date: 2026-06-28 12:02:36.786017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9dbdd6eae9b'
down_revision: Union[str, Sequence[str], None] = '0768645bdd7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_data_id', sa.Integer(), nullable=False),
    sa.Column('queue_score', sa.Float(), nullable=False),
    sa.Column('queue_label', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sensor_data_id'], ['sensor_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_status_id'), 'queue_status', ['id'], unique=False)
    op.drop_index(op.f('ix_crowd_status_id'), table_name='crowd_status')
    op.drop_table('crowd_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crowd_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sensor_data_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('crowd_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('crowd_label', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sensor_data_id'], ['sensor_data.id'], name=op.f('crowd_status_sensor_data_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('crowd_status_pkey'))
    )
    op.create_index(op.f('ix_crowd_status_id'), 'crowd_status', ['id'], unique=False)
    op.drop_index(op.f('ix_queue_status_id'), table_name='queue_status')
    op.drop_table('queue_status')
    # ### end Alembic commands ###
